name: Build and Deploy
on:
  push:
    branches: [ "main" ]  # Trigger on push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            erixdev/time-app-tet:latest

  deploy-to-minikube:
    needs: build-and-push
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Kubernetes Context
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
